### ISSUE TITLE
没有查询 CLASSPATH 变量

### ISSUE THREAD

**Issue by deadlineOvO** [w568w/XposedChecker#1]
当安装 Xposed 之后，从被改变的 zygote 进程开始，它下面的所有子进程都会含有名为 CLASSPATH 的环境变量（不管 Xposed 是否禁用，这个变量总是存在）  
常见值：  
 `CLASSPATH=/system/framework/XposedBridge.jar`
`CLASSPATH=/data/data/de.robv.android.xposed.installer/bin/XposedBridge.jar`

**Comment by w568w** [comment]
Ojbk 有时间我会考虑加入这个检测

**Comment by deadlineOvO** [comment]
@w568w 顺便说一下，你的 root 检查似乎没写好，拒绝授权也会出现没有 root 的提示
