### ISSUE TITLE
magisk hide 对这应用无效的吗。。

### ISSUE THREAD

**Issue by NewBugger** [w568w/XposedChecker#2]
已经对 xposed checker 指定 magisk hide 了

重启后该应用还是能检测到 root

oreo 8.1，同时有用 magisk xposed

**Comment by w568w** [comment]
xp checker 的root检测包括应用检测，可以检查一下有没有安装Root敏感的应用（比如superuser,幸运破解器之类的）

**Comment by NewBugger** [comment]
因为这是已经 xprivacylua 关掉 app list view 权限了，权限关闭是有效的，这时检测是否安装 xp installer 的那项已经 false 了

**Comment by w568w** [comment]
https://github.com/w568w/XposedChecker/blob/1000f2e5383a5e0b1e83135b02b231a5723b1c2e/app/src/main/java/com/unionpay/mobile/device/utils/RootCheckerUtils.java#L23
这里是xp checker检测的敏感包名，可以检查一下有没有安装其中的一些。如果确定xprivacy没问题，也可以看看这几个目录有没有挂载可写
https://github.com/w568w/XposedChecker/blob/1000f2e5383a5e0b1e83135b02b231a5723b1c2e/app/src/main/java/com/unionpay/mobile/device/utils/RootCheckerUtils.java#L21

**Comment by NewBugger** [comment]
1. 我大概可以肯定 xprivacylua 是好的

2. 真的.. /system /system/bin /system/xbin /vendor /vendor/bin  这几个路径都是可写的(755) ...

这咋整啊，我上了 magisk 和 magisk xposed 了诶，又不能自己 remount r

**Comment by l344976325** [comment]
我也试过了，magisk无效，但是Rootcloak可以让这个软件检测不到root

**Comment by Declarcall** [comment]
看这里 https://www.v2ex.com/t/534365

**Comment by NewBugger** [comment]
outdate and not necessary issue to be solved, closed now.
