### ISSUE TITLE
建议更新 xposed 纯 c 检测

### ISSUE THREAD

**Issue by liudongmiao** [w568w/XposedChecker#3]
1. 你目前的 main.c 简直....不可读啊。

2. 可内存中查找符号：
android 6.0+：_ZN3art9ArtMethod22xposed_callback_methodE
android 5.X: _ZN3art6mirror9ArtMethod22xposed_callback_methodE
这也是 xposed 5.X+ 以上的工作原理

**Comment by w568w** [comment]
1. 没怎么学C，见谅 
2. 高中狗比较忙，最近可能没时间维护项目，不过无论如何感谢你的建议，会抽出时间来加上的 :)
